### ISSUE TITLE
Vendedor consegue incluir atividades em oportunidades que não são dele

### ISSUE THREAD

**Issue by msantosgnu** [M2IS/vendendo#11]
Quando um vendedor entra no cadastro de nova atividade, no campo oportunidade aparecem todas as oportunidades da organização, quando acredito que deveriam aparecer apenas as oportunidades que o vendedor está gerenciando.

**Comment by isissoledad** [comment]
Corrigido. Agora o vendedor somente pode incluir atividades nas oportunidades ligadas a ele e administrador e gerente podem incluir atividades em todas as oportunidades.
