### ISSUE TITLE
Rodando o projeto localmente

### ISSUE THREAD

**Issue by felippemr** [M2IS/vendendo#15]
Olá, boa noite!

Quais são os passos pra rodar o projeto localmente?
Roda com python 2 ou 3?
Precisa de um banco de dados?

Valeuuuuu!

**Comment by msantosgnu** [comment]
Fala @felippemr!

Basicamente um pip install no requirements já vai instalar todas as dependências.
O projeto roda com python 2.
Precisa de banco de dados, de inicio o sqlite cumpre o papel.

Valeu!
